Class01 hw4 oty
pskcci/DX-01 pull request #80
Opened 2024-11-22 05:02 UTC by otation

uploading hw#4 'gradiantEx01.ipynb' file in 'hw4_pythonHW_and_math' ditectory

2024-11-24 14:49 UTC, J-WBaek requested changes
### 수정사항
* .png 파일 지우고 올리세요.
* .py파일 hw4_pythonHW_and_math안에 넣으세요.

2024-11-26 08:12 UTC, J-WBaek requested changes
hw4에 있는 .ipynb_checkpoints는 제외하고 올리세요.

2024-11-27 00:16 UTC, otation commented
> hw4에 있는 .ipynb_checkpoints는 제외하고 올리세요.

제외하고 다시 pr하였습니다

2024-11-27 01:06 UTC, J-WBaek approved these changes

2024-11-27 01:10 UTC, merged